//============================================================
// this file was autogenerated by gen-ms-tables.py
// source file: EThrottleTables.csv
// date/time: 2023/10/27 12:24:23
//============================================================
#include "EThrottleTables.h"

OutPC_T outPC;
