//============================================================
// this file was autogenerated by gen-ms-tables.py
// source file: EThrottleTables.csv
// date/time: 2023/11/23 08:59:38
//============================================================
#include "EThrottleTables.h"

OutPC_T outPC;
